name: CICD - Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  reuse:
    uses: MyDevOpsLearning01/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      app_type: nodejs
      app_name: user